# Generated by Django 2.2.2 on 2019-06-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_count',
            field=models.IntegerField(),
        ),
    ]
